version: '3.8'
services:
  rust_server:
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - pg

  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

volumes:
  pgdata: