version: "3"

services:
  server:
    build: server 
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/mydb
      - IP=0.0.0.0
      - PORT=7878
    depends_on:
      - db
    ports:
      - 7878:7878
  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./database:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
  grafana:
    user: "0"
    image: grafana/grafana-oss
    volumes:
      - ./grafana:/etc/grafana/provisioning/
    depends_on:
      - db
    ports: 
      - 3000:3000